apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 835512929652.dkr.ecr.us-east-1.amazonaws.com/mysql-image-repo:latest
          ports:
            - containerPort: 3306
