apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 835512929652.dkr.ecr.us-east-1.amazonaws.com/mysql-image-repo:latest
      ports:
        - containerPort: 3306
