apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 835512929652.dkr.ecr.us-east-1.amazonaws.com/webapp-image-repo:latest
          ports:
            - containerPort: 8080
